services:
  bookstack-db:
    image: mysql:8
    container_name: bookstack-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Zli12345
      MYSQL_DATABASE: bookstack
      MYSQL_USER: piCloudcore
      MYSQL_PASSWORD: Zli12345
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse"
      - "traefik.http.routers.bookstack.rule=Host(`bookstack.local`)"
      - "traefik.http.routers.bookstack.entrypoints=web"
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"
    restart: unless-stopped
    environment:
      - DB_HOST=bookstack-db
      - DB_USER=piCloudcore
      - DB_PASS=Zli12345
      - DB_DATABASE=bookstack
      - APP_URL=http://bookstack.local
    volumes:
      - bookstack_data:/config
    networks:
      - internal
      - reverse
    depends_on:
      - bookstack-db

volumes:
  db_data:
  bookstack_data:

networks:
  internal:
    external: true
  reverse:
    external: true