title: Projekt Dashboard
subtitle: Übersicht über alle Dienste
theme: default
logo: ""

services:
  - name: Monitoring
    icon: fas fa-chart-line
    items:
      - name: Uptime Kuma
        url: https://kuma.local
        icon: uptime-kuma.png
      - name: Traefik
        url: https://traefik.local
        icon: traefik.png
      - name: Netdata
        url: https://netdata.local
        icon: netdata.png

  - name: Tools
    icon: fas fa-toolbox
    items:
      - name: Bookstack
        url: https://bookstack.local
        icon: bookstack.png
      - name: Filebrowser
        url: https://file.local
        icon: filebrowser.png

  - name: Security
    icon:
    items:
      - name: AdGuard
        url: https://dns.local