version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - kuma-net

networks:
  kuma-net:
    external: true