version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-vol:/app/data
    networks:
      - kuma-net

volumes:
  uptime-kuma-vol:

networks:
  kuma-net:
    external: true