services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - Cloudnet
    restart: unless-stopped

networks:
  Cloudnet:
    external: true