# -------------------------------------------------------------
# Datei: docker-compose.yml
# Projekt: PLA-2 Abschlussprojekt 2025 – piCloudcore
# Autor: Jann Neururer
# Datum: 27.06.2025
# Beschreibung: Docker-Compose Datei für Nginx
# -------------------------------------------------------------
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - Cloudnet
    restart: unless-stopped

networks:
  Cloudnet:
    external: true