services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse"
      - "traefik.http.routers.kuma.rule=Host(`kuma.local`)"
      - "traefik.http.routers.kuma.entrypoints=websecure"
      - "traefik.http.routers.kuma.tls=true"
      - "traefik.http.services.kuma.loadbalancer.server.port=3001"
    networks:
      - reverse
    volumes:
      - uptime-kuma-vol:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  uptime-kuma-vol:

networks:
  reverse:
    external: true